dist: trusty
language: java
jdk:
  - openjdk8
  - oraclejdk8
script:
  - ./gradlew test
after_success:
  - ./gradlew jacocoTestReport coveralls
addons:
  hosts:
    - example.com
  hostname: example.com
